language: java

sudo: false

dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8


install: true


script:
  - ./gradlew check
  - ./gradlew  sonarqube





cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/



